### ISSUE TITLE
Solc.js compatibility issue

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/ethereum-container-broker#12]
solc.js appears not to be fully compliant with the version of solidity used in a contract. We have come to see errors like the following when deploying contracts: 

```
[number-to-bn] while converting number undefined to BN.js instance, error: 
invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "undefined"
```

One hypothesis is that contracts that have a loop in them fail to be parsed properly.

We should investigate the issue and find a solution by doing either of the two:
- raise the issue with solc.js
- fall back to using the binary version of solidity compiler (the binary appears to work fine)

**Comment by swetharepakula** [comment]
Reading this documentation: http://solidity.readthedocs.io/en/v0.4.21/installing-solidity.html#npm-node-js.

I think the solc-js (the package we are using) is known not to be as compatible. It is built based on the solc C++ binary. I think we should switch to using the binary that is the actual compiler instead.

**Comment by nimakaviani** [comment]
The commit above fixes the issue. 

closing the issue.
