### ISSUE TITLE
Have the service broker function properly on Kube.

### ISSUE THREAD

**Issue by nkaviani** [nimakaviani/ethereum-container-broker#6]
We want to demonstrate that the broker can run on Kube and that it can be used to provision Ethereum nodes and deploy smart contracts. Also we need to demonstrate that application developers will be able to deploy applications to Kube and bind to the contract service possibly by using one of the sample applications that we have already developed.

The output would be a self sufficient document explaining how to attach the service broker to Kube and how to have an application deployed to Kube bind to it and use it (plus any accompanying configuration / manifest file required)

**Comment by MHBauer** [comment]
Ooh, I hope the answer involves https://github.com/kubernetes-incubator/service-catalog/

**Comment by nimakaviani** [comment]
LGTM following the discussion in the call. will merge in.

**Comment by nimakaviani** [comment]
The documentation is merged. Also we have done some exploratory work by @swetharepakula and @jberkhahn on how we initially thought this would work.

Our finding was that the easiest to achieve this would be to have the broker deployed as a POD on Kubernetes and then use it to start other PODS for ethereum nodes and bind application PODS to them. There will be more exploratory work in #21 to further flesh out the work that needs to be done.

Closing in favor of #21
